<a href="https://colab.research.google.com/github/nrwpradana/Predict-Serie-A-Match/blob/main/Predict_Serie_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
matches = pd.read_csv("/content/matches_seriea.csv", index_col=0)

In [ ]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2022-08-15,18:30,Serie A,Matchweek 1,Mon,Away,W,5.0,2.0,Hellas Verona,...,Match Report,NaN,25.0,8.0,15.2,0.0,0,0,2022,Napoli
1,2022-08-21,18:30,Serie A,Matchweek 2,Sun,Home,W,4.0,0.0,Monza,...,Match Report,NaN,22.0,5.0,15.3,1.0,0,0,2022,Napoli
2,2022-08-28,20:45,Serie A,Matchweek 3,Sun,Away,D,0.0,0.0,Fiorentina,...,Match Report,NaN,13.0,2.0,14.7,1.0,0,0,2022,Napoli
3,2022-08-31,20:45,Serie A,Matchweek 4,Wed,Home,D,1.0,1.0,Lecce,...,Match Report,NaN,19.0,7.0,17.7,0.0,0,0,2022,Napoli
4,2022-09-03,20:45,Serie A,Matchweek 5,Sat,Away,W,2.0,1.0,Lazio,...,Match Report,NaN,19.0,7.0,16.1,0.0,0,0,2022,Napoli
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,2021-05-03,20:45,Serie A,Matchweek 34,Mon,Away,L,0.0,1.0,Torino,...,Match Report,NaN,10.0,1.0,18.1,0.0,0,0,2020,Parma
37,2021-05-09,15:00,Serie A,Matchweek 35,Sun,Home,L,2.0,5.0,Atalanta,...,Match Report,NaN,7.0,2.0,18.7,0.0,0,0,2020,Parma
38,2021-05-12,20:45,Serie A,Matchweek 36,Wed,Away,L,0.0,1.0,Lazio,...,Match Report,NaN,12.0,4.0,27.1,1.0,0,0,2020,Parma
39,2021-05-16,18:00,Serie A,Matchweek 37,Sun,Home,L,1.0,3.0,Sassuolo,...,Match Report,NaN,16.0,8.0,16.8,0.0,0,0,2020,Parma
40,2021-05-22,20:45,Serie A,Matchweek 38,Sat,Away,L,0.0,3.0,Sampdoria,...,Match Report,NaN,12.0,1.0,23.6,2.0,0,0,2020,Parma

In [ ]:
matches.shape

(1772, 27)

In [ ]:
matches["team"].value_counts()

Napoli            89
Bologna           89
Atalanta          89
Spezia            89
Udinese           89
Milan             89
Sassuolo          89
Torino            89
Hellas Verona     88
Sampdoria         88
Fiorentina        88
Juventus          88
Internazionale    88
Lazio             88
Roma              88
Cagliari          76
Genoa             76
Salernitana       51
Empoli            51
Venezia           38
Benevento         38
Crotone           38
Parma             38
Lecce             13
Cremonese         13
Monza             12
Name: team, dtype: int64

In [ ]:
matches["round"].value_counts()

Matchweek 1     60
Matchweek 2     60
Matchweek 3     60
Matchweek 4     60
Matchweek 5     60
Matchweek 6     60
Matchweek 7     60
Matchweek 8     60
Matchweek 9     60
Matchweek 10    60
Matchweek 11    60
Matchweek 12    60
Matchweek 13    52
Matchweek 37    40
Matchweek 36    40
Matchweek 35    40
Matchweek 34    40
Matchweek 33    40
Matchweek 32    40
Matchweek 26    40
Matchweek 31    40
Matchweek 30    40
Matchweek 29    40
Matchweek 28    40
Matchweek 27    40
Matchweek 20    40
Matchweek 25    40
Matchweek 24    40
Matchweek 23    40
Matchweek 22    40
Matchweek 21    40
Matchweek 19    40
Matchweek 18    40
Matchweek 17    40
Matchweek 16    40
Matchweek 15    40
Matchweek 14    40
Matchweek 38    40
Name: round, dtype: int64

In [ ]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes            object
sh              float64
sot             float64
dist            float64
fk              float64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [ ]:
del matches["comp"]

In [ ]:
del matches["notes"]

In [ ]:
matches["date"] = pd.to_datetime(matches["date"])

In [14]:
matches["target"] = (matches["result"] == "W").astype("int")

In [15]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,match report,sh,sot,dist,fk,pk,pkatt,season,team,target
0,2022-08-15,18:30,Matchweek 1,Mon,Away,W,5.0,2.0,Hellas Verona,2.4,...,Match Report,25.0,8.0,15.2,0.0,0,0,2022,Napoli,1
1,2022-08-21,18:30,Matchweek 2,Sun,Home,W,4.0,0.0,Monza,2.0,...,Match Report,22.0,5.0,15.3,1.0,0,0,2022,Napoli,1
2,2022-08-28,20:45,Matchweek 3,Sun,Away,D,0.0,0.0,Fiorentina,1.7,...,Match Report,13.0,2.0,14.7,1.0,0,0,2022,Napoli,0
3,2022-08-31,20:45,Matchweek 4,Wed,Home,D,1.0,1.0,Lecce,1.7,...,Match Report,19.0,7.0,17.7,0.0,0,0,2022,Napoli,0
4,2022-09-03,20:45,Matchweek 5,Sat,Away,W,2.0,1.0,Lazio,2.1,...,Match Report,19.0,7.0,16.1,0.0,0,0,2022,Napoli,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,2021-05-03,20:45,Matchweek 34,Mon,Away,L,0.0,1.0,Torino,0.5,...,Match Report,10.0,1.0,18.1,0.0,0,0,2020,Parma,0
37,2021-05-09,15:00,Matchweek 35,Sun,Home,L,2.0,5.0,Atalanta,0.9,...,Match Report,7.0,2.0,18.7,0.0,0,0,2020,Parma,0
38,2021-05-12,20:45,Matchweek 36,Wed,Away,L,0.0,1.0,Lazio,0.7,...,Match Report,12.0,4.0,27.1,1.0,0,0,2020,Parma,0
39,2021-05-16,18:00,Matchweek 37,Sun,Home,L,1.0,3.0,Sassuolo,1.0,...,Match Report,16.0,8.0,16.8,0.0,0,0,2020,Parma,0
40,2021-05-22,20:45,Matchweek 38,Sat,Away,L,0.0,3.0,Sampdoria,0.8,...,Match Report,12.0,1.0,23.6,2.0,0,0,2020,Parma,0

In [16]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [17]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [18]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [19]:
matches["day_code"] = matches["date"].dt.dayofweek

In [20]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
0,2022-08-15,18:30,Matchweek 1,Mon,Away,W,5.0,2.0,Hellas Verona,2.4,...,0.0,0,0,2022,Napoli,1,0,9,18,0
1,2022-08-21,18:30,Matchweek 2,Sun,Home,W,4.0,0.0,Monza,2.0,...,1.0,0,0,2022,Napoli,1,1,15,18,6
2,2022-08-28,20:45,Matchweek 3,Sun,Away,D,0.0,0.0,Fiorentina,1.7,...,1.0,0,0,2022,Napoli,0,0,7,20,6
3,2022-08-31,20:45,Matchweek 4,Wed,Home,D,1.0,1.0,Lecce,1.7,...,0.0,0,0,2022,Napoli,0,1,13,20,2
4,2022-09-03,20:45,Matchweek 5,Sat,Away,W,2.0,1.0,Lazio,2.1,...,0.0,0,0,2022,Napoli,1,0,12,20,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,2021-05-03,20:45,Matchweek 34,Mon,Away,L,0.0,1.0,Torino,0.5,...,0.0,0,0,2020,Parma,0,0,23,20,0
37,2021-05-09,15:00,Matchweek 35,Sun,Home,L,2.0,5.0,Atalanta,0.9,...,0.0,0,0,2020,Parma,0,1,0,15,6
38,2021-05-12,20:45,Matchweek 36,Wed,Away,L,0.0,1.0,Lazio,0.7,...,1.0,0,0,2020,Parma,0,0,12,20,2
39,2021-05-16,18:00,Matchweek 37,Sun,Home,L,1.0,3.0,Sassuolo,1.0,...,0.0,0,0,2020,Parma,0,1,21,18,6
40,2021-05-22,20:45,Matchweek 38,Sat,Away,L,0.0,3.0,Sampdoria,0.8,...,2.0,0,0,2020,Parma,0,0,20,20,5

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [23]:
train = matches[matches["date"] < '2022-01-01']

In [24]:
test = matches[matches["date"] > '2022-01-01']

In [25]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [26]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [27]:
preds = rf.predict(test[predictors])

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
error = accuracy_score(test["target"], preds)

In [30]:
error

0.582018927444795

In [31]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [32]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0    1
actual
0          287  116
1          149   82

In [34]:
from sklearn.metrics import precision_score
precision_score(test["target"], preds)

0.41414141414141414

In [35]:
grouped_matches = matches.groupby("team")

In [36]:
group = grouped_matches.get_group("Internazionale").sort_values("date")

In [37]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [38]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [39]:
rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2020-10-17,18:00,Matchweek 4,Sat,Home,L,1.0,2.0,Milan,2.8,...,18,5,3.333333,2.000000,17.000000,6.333333,16.900000,0.333333,0.000000,0.000000
5,2020-10-24,18:00,Matchweek 5,Sat,Away,W,2.0,0.0,Genoa,1.7,...,18,5,2.333333,1.666667,16.000000,5.333333,15.366667,0.333333,0.000000,0.000000
7,2020-10-31,18:00,Matchweek 6,Sat,Home,D,2.0,2.0,Parma,2.9,...,18,5,1.333333,1.000000,14.666667,4.000000,15.366667,0.000000,0.000000,0.000000
9,2020-11-08,15:00,Matchweek 7,Sun,Away,D,1.0,1.0,Atalanta,0.9,...,15,6,1.666667,1.333333,19.000000,6.000000,15.900000,0.000000,0.000000,0.000000
10,2020-11-22,15:00,Matchweek 8,Sun,Home,W,4.0,2.0,Torino,4.0,...,15,6,1.666667,1.000000,16.333333,5.333333,16.900000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,2022-10-01,18:00,Matchweek 8,Sat,Home,L,1.0,2.0,Roma,1.0,...,18,5,1.333333,2.000000,16.000000,4.000000,19.533333,1.333333,0.000000,0.000000
11,2022-10-08,15:00,Matchweek 9,Sat,Away,W,2.0,1.0,Sassuolo,2.3,...,15,5,1.000000,1.666667,15.666667,3.000000,19.933333,1.666667,0.000000,0.000000
13,2022-10-16,12:30,Matchweek 10,Sun,Home,W,2.0,0.0,Salernitana,1.7,...,12,6,1.333333,2.000000,15.666667,3.333333,18.733333,1.666667,0.000000,0.000000
14,2022-10-22,20:45,Matchweek 11,Sat,Away,W,4.0,3.0,Fiorentina,2.4,...,20,5,1.666667,1.000000,15.666667,4.000000,17.266667,1.333333,0.000000,0.000000
16,2022-10-29,20:45,Matchweek 12,Sat,Home,W,3.0,0.0,Sampdoria,2.0,...,20,5,2.666667,1.333333,13.000000,5.333333,14.866667,0.666667,0.333333,0.333333

In [40]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [41]:
matches_rolling

                  date   time         round  day venue result   gf   ga  \
team
Atalanta 3  2020-10-17  15:00   Matchweek 4  Sat  Away      L  1.0  4.0
         5  2020-10-24  15:00   Matchweek 5  Sat  Home      L  1.0  3.0
         7  2020-10-31  15:00   Matchweek 6  Sat  Away      W  2.0  1.0
         9  2020-11-08  15:00   Matchweek 7  Sun  Home      D  1.0  1.0
         10 2020-11-21  18:00   Matchweek 8  Sat  Away      D  0.0  0.0
...                ...    ...           ...  ...   ...    ...  ...  ...
Venezia  36 2022-05-01  12:30  Matchweek 35  Sun  Away      L  1.0  2.0
         37 2022-05-05  18:00  Matchweek 20  Thu  Away      L  1.0  2.0
         38 2022-05-08  15:00  Matchweek 36  Sun  Home      W  4.0  3.0
         39 2022-05-14  20:45  Matchweek 37  Sat  Away      D  1.0  1.0
         40 2022-05-22  21:00  Matchweek 38  Sun  Home      D  0.0  0.0

                opponent   xg  ...  hour  day_code  gf_rolling ga_rolling  \
team                           ...
Atalanta 3        Napoli  0.7  ...    15         5    4.333333   1.666667
         5     Sampdoria  2.1  ...    15         5    3.333333   2.333333
         7       Crotone  2.8  ...    15         5    2.333333   3.000000
         9         Inter  1.0  ...    15         6    1.333333   2.666667
         10       Spezia  2.1  ...    18         5    1.333333   1.666667
...                  ...  ...  ...   ...       ...         ...        ...
Venezia  36     Juventus  0.6  ...    12         6    0.666667   2.000000
         37  Salernitana  1.4  ...    18         3    0.666667   2.000000
         38      Bologna  3.2  ...    15         6    1.000000   2.333333
         39         Roma  0.3  ...    20         5    2.000000   2.333333
         40     Cagliari  0.9  ...    21         6    2.000000   2.000000

            sh_rolling sot_rolling dist_rolling  fk_rolling  pk_rolling  \
team
Atalanta 3   16.333333    8.333333    16.633333    1.000000    0.000000
         5   14.666667    7.333333    17.700000    0.666667    0.000000
         7   17.666667    6.666667    18.900000    1.000000    0.333333
         9   17.000000    4.666667    18.033333    0.666667    0.333333
         10  15.666667    4.000000    17.633333    1.333333    0.333333
...                ...         ...          ...         ...         ...
Venezia  36   6.666667    2.333333    17.200000    0.666667    0.000000
         37   6.666667    2.000000    19.400000    1.000000    0.000000
         38   9.000000    3.000000    17.766667    1.666667    0.000000
         39  11.666667    4.666667    18.433333    1.333333    0.333333
         40  10.000000    4.333333    20.000000    0.666667    0.333333

             pkatt_rolling
team
Atalanta 3        0.000000
         5        0.000000
         7        0.333333
         9        0.333333
         10       0.333333
...                    ...
Venezia  36       0.000000
         37       0.000000
         38       0.000000
         39       0.666667
         40       0.666667

[1688 rows x 38 columns]

In [42]:
matches_rolling = matches_rolling.droplevel('team')

In [43]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2020-10-17,15:00,Matchweek 4,Sat,Away,L,1.0,4.0,Napoli,0.7,...,15,5,4.333333,1.666667,16.333333,8.333333,16.633333,1.000000,0.000000,0.000000
5,2020-10-24,15:00,Matchweek 5,Sat,Home,L,1.0,3.0,Sampdoria,2.1,...,15,5,3.333333,2.333333,14.666667,7.333333,17.700000,0.666667,0.000000,0.000000
7,2020-10-31,15:00,Matchweek 6,Sat,Away,W,2.0,1.0,Crotone,2.8,...,15,5,2.333333,3.000000,17.666667,6.666667,18.900000,1.000000,0.333333,0.333333
9,2020-11-08,15:00,Matchweek 7,Sun,Home,D,1.0,1.0,Inter,1.0,...,15,6,1.333333,2.666667,17.000000,4.666667,18.033333,0.666667,0.333333,0.333333
10,2020-11-21,18:00,Matchweek 8,Sat,Away,D,0.0,0.0,Spezia,2.1,...,18,5,1.333333,1.666667,15.666667,4.000000,17.633333,1.333333,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,2022-05-01,12:30,Matchweek 35,Sun,Away,L,1.0,2.0,Juventus,0.6,...,12,6,0.666667,2.000000,6.666667,2.333333,17.200000,0.666667,0.000000,0.000000
37,2022-05-05,18:00,Matchweek 20,Thu,Away,L,1.0,2.0,Salernitana,1.4,...,18,3,0.666667,2.000000,6.666667,2.000000,19.400000,1.000000,0.000000,0.000000
38,2022-05-08,15:00,Matchweek 36,Sun,Home,W,4.0,3.0,Bologna,3.2,...,15,6,1.000000,2.333333,9.000000,3.000000,17.766667,1.666667,0.000000,0.000000
39,2022-05-14,20:45,Matchweek 37,Sat,Away,D,1.0,1.0,Roma,0.3,...,20,5,2.000000,2.333333,11.666667,4.666667,18.433333,1.333333,0.333333,0.666667
40,2022-05-22,21:00,Matchweek 38,Sun,Home,D,0.0,0.0,Cagliari,0.9,...,21,6,2.000000,2.000000,10.000000,4.333333,20.000000,0.666667,0.333333,0.666667

In [44]:
matches_rolling.index = range(matches_rolling.shape[0])

In [45]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [46]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [47]:
error

0.4774193548387097

In [48]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [49]:
combined.head(10)

    actual  predicted       date      team    opponent result
54       1          0 2022-01-09  Atalanta     Udinese      W
55       0          0 2022-01-16  Atalanta       Inter      D
56       0          0 2022-01-22  Atalanta       Lazio      D
57       0          1 2022-02-06  Atalanta    Cagliari      L
58       0          0 2022-02-13  Atalanta    Juventus      D
59       0          0 2022-02-20  Atalanta  Fiorentina      L
60       1          0 2022-02-28  Atalanta   Sampdoria      W
61       0          0 2022-03-05  Atalanta        Roma      L
62       0          0 2022-03-13  Atalanta       Genoa      D
63       1          0 2022-03-20  Atalanta     Bologna      W

In [50]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Internazionale": "Inter"} 
mapping = MissingDict(**map_values)

In [51]:
combined["new_team"] = combined["team"].map(mapping)

In [52]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [53]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,1,0,2022-01-09,Atalanta,Udinese,W,Atalanta,0,0,Udinese,Atalanta,L,Udinese
1,0,0,2022-01-16,Atalanta,Inter,D,Atalanta,0,1,Internazionale,Atalanta,D,Inter
2,0,0,2022-01-22,Atalanta,Lazio,D,Atalanta,0,0,Lazio,Atalanta,D,Lazio
3,0,1,2022-02-06,Atalanta,Cagliari,L,Atalanta,1,0,Cagliari,Atalanta,W,Cagliari
4,0,0,2022-02-13,Atalanta,Juventus,D,Atalanta,0,1,Juventus,Atalanta,D,Juventus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,0,0,2022-05-01,Venezia,Juventus,L,Venezia,1,1,Juventus,Venezia,W,Juventus
612,0,0,2022-05-05,Venezia,Salernitana,L,Venezia,1,0,Salernitana,Venezia,W,Salernitana
613,1,0,2022-05-08,Venezia,Bologna,W,Venezia,0,0,Bologna,Venezia,L,Bologna
614,0,0,2022-05-14,Venezia,Roma,D,Venezia,0,0,Roma,Venezia,D,Roma
615,0,0,2022-05-22,Venezia,Cagliari,D,Venezia,0,0,Cagliari,Venezia,D,Cagliari

In [54]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    68
0    64
Name: actual_x, dtype: int64